#!/usr/bin/env bash
# Regenerate INDEX.md by scanning every lab-NN-*/.lab-meta.yml file.
# Usage: bash scripts/list-labs.sh
#
# Parses a tiny subset of YAML: top-level scalar keys only. No nested arrays
# beyond tags, which we ignore for the index. This is intentional — we do not
# want a yaml library dependency for a learning repo.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INDEX_FILE="$REPO_ROOT/INDEX.md"

extract() {
  # extract <key> <file>  — prints the value of a top-level scalar key.
  # Strips inline `#` comments and surrounding quotes/whitespace.
  local key="$1" file="$2"
  awk -v k="$key" '
    BEGIN { re = "^" k ":[[:space:]]*" }
    $0 ~ re {
      sub(re, "", $0)
      sub(/[[:space:]]*#.*$/, "", $0)
      sub(/[[:space:]]+$/, "", $0)
      gsub(/^"|"$/, "", $0)
      gsub(/^'"'"'|'"'"'$/, "", $0)
      print
      exit
    }
  ' "$file"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Lab Index"
  echo
  echo "Auto-generated by \`scripts/list-labs.sh\`. Do not edit by hand — re-run the script after adding or changing a lab."
  echo
  echo "> Last generated: $(date -u +%Y-%m-%d)"
  echo
  echo "## Built labs"
  echo
  echo "| Section | Lab | Difficulty | Est. |"
  echo "|---|---|---|---|"
} > "$tmp"

built_count=0
total_minutes=0

# shellcheck disable=SC2044
# Only scan numbered section dirs (NN-*), not templates/ or other subtrees.
for meta in $(find "$REPO_ROOT" -mindepth 3 -maxdepth 3 -name '.lab-meta.yml' -path "$REPO_ROOT/[0-9][0-9]-*" | sort); do
  lab_dir="$(dirname "$meta")"
  section_dir="$(basename "$(dirname "$lab_dir")")"
  lab_slug="$(basename "$lab_dir")"

  title="$(extract title "$meta")"
  difficulty="$(extract difficulty "$meta")"
  est="$(extract est_minutes "$meta")"

  [[ -z "$title" ]] && title="$lab_slug"
  [[ -z "$difficulty" ]] && difficulty="beginner"
  [[ -z "$est" ]] && est="?"

  printf '| %s | [%s](%s/%s/) | %s | %s min |\n' \
    "$section_dir" "$lab_slug" "$section_dir" "$lab_slug" "$difficulty" "$est" \
    >> "$tmp"

  built_count=$((built_count + 1))
  if [[ "$est" =~ ^[0-9]+$ ]]; then
    total_minutes=$((total_minutes + est))
  fi
done

{
  echo
  echo "**Total built: ${built_count} labs · ~${total_minutes} min of practice**"
  echo
  echo "## Planned sections (stubs)"
  echo
  echo "| Section | Status | Ships in |"
  echo "|---|---|---|"
} >> "$tmp"

for section_meta in $(find "$REPO_ROOT" -mindepth 2 -maxdepth 2 -name 'SECTION.md' | sort); do
  section_dir="$(basename "$(dirname "$section_meta")")"
  status="$(awk -F': *' '/^status:/ {gsub(/"/, "", $2); print $2; exit}' "$section_meta")"
  ships_in="$(awk -F': *' '/^ships_in:/ {gsub(/"/, "", $2); print $2; exit}' "$section_meta")"
  [[ -z "$status" ]] && status="planned"
  [[ -z "$ships_in" ]] && ships_in="?"

  if [[ "$status" != "ready" ]]; then
    printf '| [%s](%s/) | %s | %s |\n' "$section_dir" "$section_dir" "$status" "$ships_in" >> "$tmp"
  fi
done

mv "$tmp" "$INDEX_FILE"
trap - EXIT

echo "Regenerated $INDEX_FILE ($built_count built labs)"
